/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Confirm */
        post: operations["password_reset_confirm_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Request */
        post: operations["password_reset_request_api_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_v1_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feed
         * @description ホームフィード / 検索（features/home-feed.md・search.md）。
         *
         *     受け付ける `feed` は `all` / `following` / `followers`。`favorites` は
         *     お気に入り機能の Issue で有効化するので、今はまだ 400 にする
         *     （home-feed.md §6「不正値は 400」）。`q` はどの `feed` とも併用できる。
         */
        get: operations["list_feed_api_v1_recipes_get"];
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_api_v1_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_v1_recipes__recipe_id__get"];
        /** Update Recipe */
        put: operations["update_recipe_api_v1_recipes__recipe_id__put"];
        post?: never;
        /** Delete Recipe */
        delete: operations["delete_recipe_api_v1_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Recipe View
         * @description レシピ詳細を開いた記録を残す（features/view-history.md §3）。
         *
         *     クライアントは `GET /recipes/{id}` 成功後に非同期で 1 回だけ呼ぶ。
         *     見えないレシピは 404、成功は 204（body なし）。書き込みなので commit を明示する。
         */
        post: operations["record_recipe_view_api_v1_recipes__recipe_id__view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Units */
        get: operations["list_units_api_v1_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Followers
         * @description 自分をフォローしているユーザー一覧。
         *
         *     各要素の `isFollowing` は「自分がその人をフォローしているか」なので、
         *     画面ではフォローバック済みかどうかの判定に使える（follow.md §5）。
         */
        get: operations["list_my_followers_api_v1_users_me_followers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Following
         * @description 自分がフォローしているユーザー一覧。
         *
         *     `GET /users/{id}/following` に自分の ID を渡した場合と同じ内容を返す
         *     ショートカット（follow.md §5）。クライアントが自分の ID を持っていなくても
         *     呼べるようにするためのもの。
         */
        get: operations["list_my_following_api_v1_users_me_following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My History
         * @description 最近見たレシピ一覧（features/view-history.md §5）。読み取りのみ。
         */
        get: operations["get_my_history_api_v1_users_me_history_get"];
        put?: never;
        post?: never;
        /**
         * Delete My History
         * @description 閲覧履歴を全消去する（features/view-history.md §5）。
         *
         *     書き込みなので、レスポンスを返す前に明示的に commit する（ファイル冒頭コメント）。
         */
        delete: operations["delete_my_history_api_v1_users_me_history_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Recipes */
        get: operations["list_my_recipes_api_v1_users_me_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description ユーザープロフィール（features/profile.md §5 の最小版）。
         *
         *     アバター・メール・SNS リンク・公開トグルはプロフィール拡張の Issue で足す。
         */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Follow User
         * @description `user_id` をフォローする。冪等（二重フォローでも 204）。
         *
         *     `run_with_retry` で包む理由: 同じ相手に同時フォローが来ると `users` 行の
         *     ロック待ちが発生し、まれにデッドロックで中断されることがある。
         *     そのときはサーバー側でやり直し、クライアントにはエラーを見せない
         *     （follow.md §3 / non-functional.md）。commit も `run_with_retry` が行う。
         */
        post: operations["follow_user_api_v1_users__user_id__follow_post"];
        /**
         * Unfollow User
         * @description フォローを解除する。フォローしていなくても 204（冪等）。
         */
        delete: operations["unfollow_user_api_v1_users__user_id__follow_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Followers
         * @description `user_id` のユーザーをフォローしているユーザー一覧。
         */
        get: operations["list_user_followers_api_v1_users__user_id__followers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Following
         * @description `user_id` のユーザーがフォローしているユーザー一覧。
         */
        get: operations["list_user_following_api_v1_users__user_id__following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロセスの生存確認
         * @description プロセスが起動していれば 200 を返すだけの軽いエンドポイント。
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * DB への疎通確認
         * @description DB に `SELECT 1` できるかを返す。つながらなくても例外にはしない。
         */
        get: operations["healthz_db_healthz_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthTokenResponse */
        AuthTokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
            user: components["schemas"]["UserPublic"];
        };
        /** Body_upload_image_api_v1_images_post */
        Body_upload_image_api_v1_images_post: {
            /**
             * File
             * @description JPEG / PNG / WebP の画像 1 枚
             */
            file: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        ErrorEnvelope: {
            error: {
                code: string;
                details?: Record<string, never> | null;
                message: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryItem
         * @description 閲覧履歴の 1 件。フィードのカード形状 ＋ 「最後に見た時刻」（view-history.md §5）。
         */
        HistoryItem: {
            author: components["schemas"]["RecipeAuthor"];
            /** Favoritecount */
            favoriteCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Thumbnailurl */
            thumbnailUrl: string | null;
            /** Title */
            title: string;
            /**
             * Viewedat
             * Format: date-time
             */
            viewedAt: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /**
         * ImageUploadResponse
         * @description 一時アップロードの結果。
         *
         *     `key` はレシピ保存時に `thumbnailKey` / `steps[].imageKey` として送り返す
         *     ためのもの。`url` はアップロード直後のプレビュー表示に使う。
         */
        ImageUploadResponse: {
            /**
             * Key
             * @description オブジェクトキー。レシピ保存時にこの値を送る
             */
            key: string;
            /**
             * Url
             * @description 表示用 URL（プレビュー用）
             */
            url: string;
        };
        /** IngredientGroupInput */
        IngredientGroupInput: {
            /** Ingredients */
            ingredients: components["schemas"]["IngredientInput"][];
            /** Name */
            name?: string | null;
        };
        /** IngredientGroupOutput */
        IngredientGroupOutput: {
            /** Ingredients */
            ingredients: components["schemas"]["IngredientOutput"][];
            /** Name */
            name: string | null;
        };
        /** IngredientInput */
        IngredientInput: {
            /** Name */
            name: string;
            /** Quantity */
            quantity?: number | string | null;
            /** Refrecipeid */
            refRecipeId?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /** IngredientOutput */
        IngredientOutput: {
            /** Name */
            name: string;
            /** Placement */
            placement: string;
            /** Quantity */
            quantity: string | null;
            refRecipe: components["schemas"]["RefRecipe"] | null;
            /** Unit */
            unit: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Rememberme
             * @default false
             */
            rememberMe: boolean;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /** PasswordResetConfirmRequest */
        PasswordResetConfirmRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Newpassword */
            newPassword: string;
            /** Securityanswer */
            securityAnswer: string;
        };
        /** PasswordResetRequestRequest */
        PasswordResetRequestRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PasswordResetRequestResponse */
        PasswordResetRequestResponse: {
            /** Securityquestion */
            securityQuestion: string;
        };
        /** RecipeAuthor */
        RecipeAuthor: {
            /** Avatarurl */
            avatarUrl?: string | null;
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * RecipeFeedItem
         * @description ホームフィードのレシピカード 1 枚分（features/home-feed.md §5）。
         *
         *     自分のレシピ一覧（`RecipeSummary`）と違い、他人のレシピも並ぶので
         *     投稿者情報（`author`）を含める。`is_public` は公開レシピしか出さないため
         *     持たせない。`favorite_count` は `recipes.favorite_count`（カウント列
         *     キャッシュ）をそのまま返す（Phase 6 でお気に入り機能が入るまでは 0）。
         */
        RecipeFeedItem: {
            author: components["schemas"]["RecipeAuthor"];
            /** Favoritecount */
            favoriteCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Thumbnailurl */
            thumbnailUrl: string | null;
            /** Title */
            title: string;
        };
        /** RecipeFeedResponse */
        RecipeFeedResponse: {
            /** Items */
            items: components["schemas"]["RecipeFeedItem"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** RecipeListResponse */
        RecipeListResponse: {
            /** Items */
            items: components["schemas"]["RecipeSummary"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** RecipeResponse */
        RecipeResponse: {
            author: components["schemas"]["RecipeAuthor"];
            /** Commentcount */
            commentCount: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Description */
            description: string;
            /** Favoritecount */
            favoriteCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ingredientgroups */
            ingredientGroups: components["schemas"]["IngredientGroupOutput"][];
            /** Isfavorited */
            isFavorited: boolean;
            /** Ispublic */
            isPublic: boolean;
            /** Servings */
            servings: number;
            /** Steps */
            steps: components["schemas"]["StepOutput"][];
            /** Thumbnailkey */
            thumbnailKey: string | null;
            /** Thumbnailurl */
            thumbnailUrl: string | null;
            /** Title */
            title: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * RecipeSummary
         * @description 自分のレシピ一覧のカード 1 枚分（features/recipe.md §2「自分のレシピ一覧」）。
         */
        RecipeSummary: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ispublic */
            isPublic: boolean;
            /** Thumbnailurl */
            thumbnailUrl: string | null;
            /** Title */
            title: string;
        };
        /**
         * RecipeWriteRequest
         * @description `POST /recipes` と `PUT /recipes/{id}` 共通のリクエスト body。
         *
         *     `PUT` の「`thumbnailKey` 省略 = サムネイル変更なし」は、ルーター側で
         *     `model_fields_set` に `"thumbnail_key"` が含まれるかで判定する
         *     （features/recipe.md §5「省略 = 変更なし / null = 削除 / 既存キー再送 = 維持 /
         *     新キー = 差し替え」）。
         */
        RecipeWriteRequest: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Ingredientgroups */
            ingredientGroups: components["schemas"]["IngredientGroupInput"][];
            /**
             * Ispublic
             * @default false
             */
            isPublic: boolean;
            /** Servings */
            servings: number;
            /** Steps */
            steps: components["schemas"]["StepInput"][];
            /** Thumbnailkey */
            thumbnailKey?: string | null;
            /** Title */
            title: string;
        };
        /** RefRecipe */
        RefRecipe: {
            /** Id */
            id: string | null;
            /** Title */
            title: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Displayname */
            displayName: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Securityanswer */
            securityAnswer: string;
            /** Securityquestion */
            securityQuestion: string;
        };
        /** StepInput */
        StepInput: {
            /** Body */
            body: string;
            /** Imagekey */
            imageKey?: string | null;
        };
        /** StepOutput */
        StepOutput: {
            /** Body */
            body: string;
            /** Imagekey */
            imageKey: string | null;
            /** Imageurl */
            imageUrl: string | null;
        };
        /** UnitOption */
        UnitOption: {
            /** Placement */
            placement: string;
            /** Value */
            value: string;
        };
        /** UnitsResponse */
        UnitsResponse: {
            /** Units */
            units: components["schemas"]["UnitOption"][];
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Displayname */
            displayName: string;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /** Displayname */
            displayName: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * UserProfileResponse
         * @description `GET /users/{id}` の最小版（features/profile.md §5）。
         *
         *     アバター・メール・SNS リンク・公開トグルはプロフィール拡張の Issue で足す。
         */
        UserProfileResponse: {
            /** Avatarurl */
            avatarUrl?: string | null;
            /** Displayname */
            displayName: string;
            /** Followercount */
            followerCount: number;
            /** Followingcount */
            followingCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isfollowing */
            isFollowing: boolean | null;
        };
        /** UserPublic */
        UserPublic: {
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * UserRow
         * @description 一覧の 1 行（アバター + 表示名 + フォロー状態ボタン）。
         */
        UserRow: {
            /** Avatarurl */
            avatarUrl?: string | null;
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isfollowing */
            isFollowing: boolean;
        };
        /** UserRowListResponse */
        UserRowListResponse: {
            /** Items */
            items: components["schemas"]["UserRow"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    password_reset_confirm_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    password_reset_request_api_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetRequestResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    upload_image_api_v1_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_v1_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_feed_api_v1_recipes_get: {
        parameters: {
            query?: {
                feed?: string;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeFeedResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_recipe_api_v1_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_recipe_api_v1_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_recipe_api_v1_recipes__recipe_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_recipe_api_v1_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    record_recipe_view_api_v1_recipes__recipe_id__view_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_units_api_v1_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitsResponse"];
                };
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_my_followers_api_v1_users_me_followers_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRowListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_my_following_api_v1_users_me_following_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRowListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_my_history_api_v1_users_me_history_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_my_history_api_v1_users_me_history_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_my_recipes_api_v1_users_me_recipes_get: {
        parameters: {
            query?: {
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    follow_user_api_v1_users__user_id__follow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    unfollow_user_api_v1_users__user_id__follow_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_user_followers_api_v1_users__user_id__followers_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRowListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_user_following_api_v1_users__user_id__following_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRowListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    healthz_db_healthz_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
