/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Confirm */
        post: operations["password_reset_confirm_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Request */
        post: operations["password_reset_request_api_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Comment
         * @description 感想の投稿者、またはレシピの投稿者が感想を削除する。
         */
        delete: operations["delete_comment_api_v1_comments__comment_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Comment
         * @description 自分の感想の本文・画像を変える（送られた項目だけ）。
         */
        patch: operations["update_comment_api_v1_comments__comment_id__patch"];
        trace?: never;
    };
    "/api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_v1_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications
         * @description 自分あての通知を新しい順に返す（未読件数を同梱）。
         */
        get: operations["list_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Read
         * @description 既読にする。`ids` 省略（body ごと省略も可）で自分の通知をすべて既読に。
         */
        post: operations["mark_read_api_v1_notifications_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Unread Count
         * @description 未読件数（バッジ用）。一覧の `unreadCount` と同じ値。
         */
        get: operations["get_unread_count_api_v1_notifications_unread_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feed
         * @description ホームフィード / 検索（features/home-feed.md・search.md）。
         *
         *     受け付ける `feed` は `all` / `following` / `followers` / `favorites`。
         *     それ以外は 400（home-feed.md §6）。`q` はどの `feed` とも併用できる。
         */
        get: operations["list_feed_api_v1_recipes_get"];
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_api_v1_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_v1_recipes__recipe_id__get"];
        /** Update Recipe */
        put: operations["update_recipe_api_v1_recipes__recipe_id__put"];
        post?: never;
        /** Delete Recipe */
        delete: operations["delete_recipe_api_v1_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Comments
         * @description そのレシピの感想を新しい順に返す。他人の非公開レシピは 404。
         */
        get: operations["list_comments_api_v1_recipes__recipe_id__comments_get"];
        put?: never;
        /**
         * Create Comment
         * @description 感想を投稿する（レシピ投稿者本人は 403）。
         */
        post: operations["create_comment_api_v1_recipes__recipe_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Favorite Recipe
         * @description お気に入りに登録する（冪等・204。features/favorite.md §5）。
         *
         *     公開レシピと自分の非公開レシピだけが対象。他人の非公開・存在しないレシピは 404。
         *     同じレシピへの同時登録で起きうるデッドロック等は `run_with_retry` がやり直し、
         *     commit まで済ませてから返す。
         */
        post: operations["favorite_recipe_api_v1_recipes__recipe_id__favorite_post"];
        /**
         * Unfavorite Recipe
         * @description お気に入りを解除する（冪等・204）。未登録・存在しないレシピでも 204。
         */
        delete: operations["unfavorite_recipe_api_v1_recipes__recipe_id__favorite_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Recipe View
         * @description レシピ詳細を開いた記録を残す（features/view-history.md §3）。
         *
         *     クライアントは `GET /recipes/{id}` 成功後に非同期で 1 回だけ呼ぶ。
         *     見えないレシピは 404、成功は 204（body なし）。書き込みなので commit を明示する。
         */
        post: operations["record_recipe_view_api_v1_recipes__recipe_id__view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Units */
        get: operations["list_units_api_v1_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description アカウントを削除する（features/profile.md §5。確認はクライアントのダイアログ）。
         *
         *     本人のデータは CASCADE で消え、画像は削除キューへ、他人のカウント列は同じ
         *     トランザクションで減らす（app/services/account.py）。デッドロックで中断されたら
         *     `run_with_retry` がやり直す。以降、同じトークンでのリクエストは 401 になる。
         */
        delete: operations["delete_me_api_v1_users_me_delete"];
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description 自分のプロフィール設定を**送られた項目だけ**更新する（features/profile.md §5）。
         */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put My Avatar
         * @description アバターを設定 / 差し替えする（features/image.md §3・§5）。
         *
         *     保存の手順（管理行 → ストレージ → 確定）は `services/user.py` の `set_avatar`。
         *     最後の確定のトランザクションをここで commit してから URL を返す。
         */
        put: operations["put_my_avatar_api_v1_users_me_avatar_put"];
        post?: never;
        /**
         * Delete My Avatar
         * @description アバターを外す。設定していなくても 204（冪等）。
         */
        delete: operations["delete_my_avatar_api_v1_users_me_avatar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Favorites
         * @description 自分のお気に入り一覧（features/favorite.md §5）。
         *
         *     お気に入りした日時の新しい順。自分の非公開レシピは含み、他人のレシピで
         *     非公開化されたものは含まない。`GET /recipes?feed=favorites` と同じ内容。
         */
        get: operations["list_my_favorites_api_v1_users_me_favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Followers
         * @description 自分をフォローしているユーザー一覧。
         *
         *     各要素の `isFollowing` は「自分がその人をフォローしているか」なので、
         *     画面ではフォローバック済みかどうかの判定に使える（follow.md §5）。
         */
        get: operations["list_my_followers_api_v1_users_me_followers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Following
         * @description 自分がフォローしているユーザー一覧。
         *
         *     `GET /users/{id}/following` に自分の ID を渡した場合と同じ内容を返す
         *     ショートカット（follow.md §5）。クライアントが自分の ID を持っていなくても
         *     呼べるようにするためのもの。
         */
        get: operations["list_my_following_api_v1_users_me_following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My History
         * @description 最近見たレシピ一覧（features/view-history.md §5）。読み取りのみ。
         */
        get: operations["get_my_history_api_v1_users_me_history_get"];
        put?: never;
        post?: never;
        /**
         * Delete My History
         * @description 閲覧履歴を全消去する（features/view-history.md §5）。
         *
         *     書き込みなので、レスポンスを返す前に明示的に commit する（ファイル冒頭コメント）。
         */
        delete: operations["delete_my_history_api_v1_users_me_history_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Recipes */
        get: operations["list_my_recipes_api_v1_users_me_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description ユーザープロフィール（features/profile.md §5）。
         *
         *     自分自身なら全項目 ＋ 公開トグルの状態、他人なら公開 ON の項目だけを返す
         *     （non-functional.md「データの可視性ルール」。組み立ては `services/user.py`）。
         */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Follow User
         * @description `user_id` をフォローする。冪等（二重フォローでも 204）。
         *
         *     `run_with_retry` で包む理由: 同じ相手に同時フォローが来ると `users` 行の
         *     ロック待ちが発生し、まれにデッドロックで中断されることがある。
         *     そのときはサーバー側でやり直し、クライアントにはエラーを見せない
         *     （follow.md §3 / non-functional.md）。commit も `run_with_retry` が行う。
         */
        post: operations["follow_user_api_v1_users__user_id__follow_post"];
        /**
         * Unfollow User
         * @description フォローを解除する。フォローしていなくても 204（冪等）。
         */
        delete: operations["unfollow_user_api_v1_users__user_id__follow_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Followers
         * @description `user_id` のユーザーをフォローしているユーザー一覧。
         */
        get: operations["list_user_followers_api_v1_users__user_id__followers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Following
         * @description `user_id` のユーザーがフォローしているユーザー一覧。
         */
        get: operations["list_user_following_api_v1_users__user_id__following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Recipes
         * @description あるユーザーのレシピ一覧（features/profile.md §5）。
         *
         *     他人が見れば公開レシピだけ、本人が見れば非公開も含む。存在しないユーザーは 404。
         */
        get: operations["list_user_recipes_api_v1_users__user_id__recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロセスの生存確認
         * @description プロセスが起動していれば 200 を返すだけの軽いエンドポイント。
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * DB への疎通確認
         * @description DB に `SELECT 1` できるかを返す。つながらなくても例外にはしない。
         */
        get: operations["healthz_db_healthz_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthTokenResponse */
        AuthTokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
            user: components["schemas"]["UserPublic"];
        };
        /**
         * AvatarResponse
         * @description `PUT /users/me/avatar` の結果（features/image.md §5）。
         *
         *     アバターは専用エンドポイントで保存まで完結するので、キーは返さない
         *     （クライアントがキーを送り返す場面が無い）。表示用 URL だけを返す。
         */
        AvatarResponse: {
            /**
             * Avatarurl
             * @description 設定したアバターの表示用 URL
             */
            avatarUrl: string;
        };
        /** Body_put_my_avatar_api_v1_users_me_avatar_put */
        Body_put_my_avatar_api_v1_users_me_avatar_put: {
            /**
             * File
             * @description JPEG / PNG / WebP の画像 1 枚
             */
            file: string;
        };
        /** Body_upload_image_api_v1_images_post */
        Body_upload_image_api_v1_images_post: {
            /**
             * File
             * @description JPEG / PNG / WebP の画像 1 枚
             */
            file: string;
        };
        /**
         * CommentCreateRequest
         * @description `POST /recipes/{id}/comments` の body。本文は必須、画像は任意。
         */
        CommentCreateRequest: {
            /** Body */
            body: string;
            /** Imagekey */
            imageKey?: string | null;
        };
        /** CommentListResponse */
        CommentListResponse: {
            /** Items */
            items: components["schemas"]["CommentResponse"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /**
         * CommentResponse
         * @description 感想 1 件（features/comment.md §5）。
         *
         *     `imageUrl` と `author.avatarUrl` は、保存したオブジェクトキーから組み立てる
         *     表示用の派生値（features/image.md §4）。
         */
        CommentResponse: {
            author: components["schemas"]["RecipeAuthor"];
            /** Body */
            body: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Imageurl */
            imageUrl: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * CommentUpdateRequest
         * @description `PATCH /comments/{id}` の body。**送られた項目だけ**を変える。
         *
         *     - `body`: 送られたら 1〜1000 文字で検証して置き換える。**null は送れない**
         *       （本文は必須の列）。OpenAPI 上も「任意だが null ではない」にするため、
         *       null を型から隠す `SkipJsonSchema[None]` を使う。`str | None` のままだと、
         *       生成される frontend の型が `body: null` を許してしまい、実際には 400 になる
         *       という契約の食い違いが起きる
         *     - `image_key`: 省略 = 変更なし / 今と同じキー = 維持 / null = 削除 /
         *       新しいキー = 差し替え（image.md §3）。null に意味があるので nullable
         *     - どちらも送られていない `{}` は 400
         */
        CommentUpdateRequest: {
            /** Body */
            body?: string;
            /** Imagekey */
            imageKey?: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        ErrorEnvelope: {
            error: {
                code: string;
                details?: Record<string, never> | null;
                message: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryItem
         * @description 閲覧履歴の 1 件。フィードのカード形状 ＋ 「最後に見た時刻」（view-history.md §5）。
         */
        HistoryItem: {
            author: components["schemas"]["RecipeAuthor"];
            /** Favoritecount */
            favoriteCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isfavorited */
            isFavorited: boolean;
            /** Thumbnailurl */
            thumbnailUrl: string | null;
            /** Title */
            title: string;
            /**
             * Viewedat
             * Format: date-time
             */
            viewedAt: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /**
         * ImageUploadResponse
         * @description 一時アップロードの結果。
         *
         *     `key` はレシピ保存時に `thumbnailKey` / `steps[].imageKey` として送り返す
         *     ためのもの。`url` はアップロード直後のプレビュー表示に使う。
         */
        ImageUploadResponse: {
            /**
             * Key
             * @description オブジェクトキー。レシピ保存時にこの値を送る
             */
            key: string;
            /**
             * Url
             * @description 表示用 URL（プレビュー用）
             */
            url: string;
        };
        /** IngredientGroupInput */
        IngredientGroupInput: {
            /** Ingredients */
            ingredients: components["schemas"]["IngredientInput"][];
            /** Name */
            name?: string | null;
        };
        /** IngredientGroupOutput */
        IngredientGroupOutput: {
            /** Ingredients */
            ingredients: components["schemas"]["IngredientOutput"][];
            /** Name */
            name: string | null;
        };
        /** IngredientInput */
        IngredientInput: {
            /** Name */
            name: string;
            /** Quantity */
            quantity?: number | string | null;
            /** Refrecipeid */
            refRecipeId?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /** IngredientOutput */
        IngredientOutput: {
            /** Name */
            name: string;
            /** Placement */
            placement: string;
            /** Quantity */
            quantity: string | null;
            refRecipe: components["schemas"]["RefRecipe"] | null;
            /** Unit */
            unit: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Rememberme
             * @default false
             */
            rememberMe: boolean;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /**
         * MarkReadRequest
         * @description `POST /notifications/read` の body。
         *
         *     - `ids` を送る → その ID のうち**自分あて**のものだけ既読にする（他人あて・存在しない
         *       ID は黙って無視する。notification.md §6）
         *     - `ids` を省略（`{}`、または body ごと省略）→ 自分の通知をすべて既読にする
         *     - `ids: null` は 400。全件既読は取り消せないので、明示の null を「全件」の意味に
         *       しない（送り間違いで全部既読になる事故を防ぐ）。null を型から隠すため
         *       `SkipJsonSchema[None]` を使う（OpenAPI 上は「任意だが null ではない」）
         */
        MarkReadRequest: {
            /** Ids */
            ids?: string[];
        };
        /**
         * NotificationComment
         * @description 感想の通知で、どの感想かを指す（遷移先の特定用。本文は出さない）。
         */
        NotificationComment: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** NotificationItem */
        NotificationItem: {
            actor: components["schemas"]["RecipeAuthor"];
            comment: components["schemas"]["NotificationComment"] | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Readat */
            readAt: string | null;
            recipe: components["schemas"]["NotificationRecipe"] | null;
            /**
             * Type
             * @enum {string}
             */
            type: "followed" | "recipe_favorited" | "recipe_commented" | "followee_new_recipe";
        };
        /** NotificationListResponse */
        NotificationListResponse: {
            /** Items */
            items: components["schemas"]["NotificationItem"][];
            /** Nextcursor */
            nextCursor: string | null;
            /** Unreadcount */
            unreadCount: number;
        };
        /**
         * NotificationRecipe
         * @description 通知の遷移先レシピ（タイトルは本文の「『肉じゃが』を〜」に使う）。
         */
        NotificationRecipe: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
        };
        /** PasswordResetConfirmRequest */
        PasswordResetConfirmRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Newpassword */
            newPassword: string;
            /** Securityanswer */
            securityAnswer: string;
        };
        /** PasswordResetRequestRequest */
        PasswordResetRequestRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PasswordResetRequestResponse */
        PasswordResetRequestResponse: {
            /** Securityquestion */
            securityQuestion: string;
        };
        /**
         * ProfileLinks
         * @description 他人向けプロフィールの SNS リンク。**公開 ON かつ値があるものだけ**入る。
         *
         *     どの項目も既定値 `None` にしておくのが大事。既定値が無いと Pydantic は
         *     OpenAPI でこれらを「必須」と宣言してしまい、「必須と言いながら実際には
         *     返さない」契約の矛盾になる（生成される frontend の型も食い違う）。
         */
        ProfileLinks: {
            /** Instagram */
            instagram?: string | null;
            /** Other */
            other?: string | null;
            /** X */
            x?: string | null;
        };
        /** RecipeAuthor */
        RecipeAuthor: {
            /** Avatarurl */
            avatarUrl?: string | null;
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * RecipeFeedItem
         * @description ホームフィードのレシピカード 1 枚分（features/home-feed.md §5）。
         *
         *     ホームフィード（全体 / フォロー / フォロワー / お気に入りレシピ）・
         *     `GET /users/me/favorites`・閲覧履歴（`HistoryItem` が継承）で共通。
         *     `is_public` は公開レシピ（とお気に入りでは自分の非公開）しか出さないため
         *     持たせない。`favorite_count` は `recipes.favorite_count`（カウント列
         *     キャッシュ）をそのまま返す。
         */
        RecipeFeedItem: {
            author: components["schemas"]["RecipeAuthor"];
            /** Favoritecount */
            favoriteCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isfavorited */
            isFavorited: boolean;
            /** Thumbnailurl */
            thumbnailUrl: string | null;
            /** Title */
            title: string;
        };
        /** RecipeFeedResponse */
        RecipeFeedResponse: {
            /** Items */
            items: components["schemas"]["RecipeFeedItem"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** RecipeListResponse */
        RecipeListResponse: {
            /** Items */
            items: components["schemas"]["RecipeSummary"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** RecipeResponse */
        RecipeResponse: {
            author: components["schemas"]["RecipeAuthor"];
            /** Commentcount */
            commentCount: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Description */
            description: string;
            /** Favoritecount */
            favoriteCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ingredientgroups */
            ingredientGroups: components["schemas"]["IngredientGroupOutput"][];
            /** Isfavorited */
            isFavorited: boolean;
            /** Ispublic */
            isPublic: boolean;
            /** Servings */
            servings: number;
            /** Steps */
            steps: components["schemas"]["StepOutput"][];
            /** Thumbnailkey */
            thumbnailKey: string | null;
            /** Thumbnailurl */
            thumbnailUrl: string | null;
            /** Title */
            title: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * RecipeSummary
         * @description ユーザーごとのレシピ一覧のカード 1 枚分。
         *
         *     `GET /users/me/recipes`（自分のレシピ一覧）と `GET /users/{id}/recipes`
         *     （ユーザープロフィールのレシピ一覧）で共通。
         *
         *     レシピカード（screens/components.md）は全一覧で投稿者（アバター ＋ 表示名）と
         *     お気に入り数を出すため、`author` と `favorite_count` を Issue #67 で足した。
         *     frontend はこの型を名前で参照している（`features/recipe/api.ts`）ので、
         *     **名前と既存の項目は変えず、項目を足すだけ**にしている。
         *     `is_public` は本人が見るときに「非公開」バッジを出すのに使う。
         */
        RecipeSummary: {
            author: components["schemas"]["RecipeAuthor"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Favoritecount */
            favoriteCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isfavorited */
            isFavorited: boolean;
            /** Ispublic */
            isPublic: boolean;
            /** Thumbnailurl */
            thumbnailUrl: string | null;
            /** Title */
            title: string;
        };
        /**
         * RecipeWriteRequest
         * @description `POST /recipes` と `PUT /recipes/{id}` 共通のリクエスト body。
         *
         *     `PUT` の「`thumbnailKey` 省略 = サムネイル変更なし」は、ルーター側で
         *     `model_fields_set` に `"thumbnail_key"` が含まれるかで判定する
         *     （features/recipe.md §5「省略 = 変更なし / null = 削除 / 既存キー再送 = 維持 /
         *     新キー = 差し替え」）。
         */
        RecipeWriteRequest: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Ingredientgroups */
            ingredientGroups: components["schemas"]["IngredientGroupInput"][];
            /**
             * Ispublic
             * @default false
             */
            isPublic: boolean;
            /** Servings */
            servings: number;
            /** Steps */
            steps: components["schemas"]["StepInput"][];
            /** Thumbnailkey */
            thumbnailKey?: string | null;
            /** Title */
            title: string;
        };
        /** RefRecipe */
        RefRecipe: {
            /** Id */
            id: string | null;
            /** Title */
            title: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Displayname */
            displayName: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Securityanswer */
            securityAnswer: string;
            /** Securityquestion */
            securityQuestion: string;
        };
        /** StepInput */
        StepInput: {
            /** Body */
            body: string;
            /** Imagekey */
            imageKey?: string | null;
        };
        /** StepOutput */
        StepOutput: {
            /** Body */
            body: string;
            /** Imagekey */
            imageKey: string | null;
            /** Imageurl */
            imageUrl: string | null;
        };
        /** UnitOption */
        UnitOption: {
            /** Placement */
            placement: string;
            /** Value */
            value: string;
        };
        /** UnitsResponse */
        UnitsResponse: {
            /** Units */
            units: components["schemas"]["UnitOption"][];
        };
        /** UnreadCountResponse */
        UnreadCountResponse: {
            /** Unreadcount */
            unreadCount: number;
        };
        /**
         * UpdateMeRequest
         * @description `PATCH /users/me` の body（features/profile.md §5）。
         *
         *     ## 「送られた項目だけ更新する」の作り方
         *
         *     すべての項目を任意にし、**既定値を `None` にする**。Pydantic v2 では
         *     `str | None` と書くだけだと「null も入れられる必須項目」になってしまい、
         *     表示名だけ送る、といった部分更新ができない。
         *
         *     そのうえで、「送られなかった」と「null が送られた」を区別する必要がある
         *     （どちらも値は `None` になる）。区別には Pydantic が記録している
         *     `model_fields_set`（＝リクエストに実際に含まれていた項目名）を使う。
         *     - 送られなかった → 変更しない
         *     - URL に null → 削除する
         *     - 表示名・トグルに null → 400（DB では NOT NULL の列なので、ここで弾く）
         */
        UpdateMeRequest: {
            /** Displayname */
            displayName?: string | null;
            /** Emailpublic */
            emailPublic?: boolean | null;
            /** Instagrampublic */
            instagramPublic?: boolean | null;
            /** Instagramurl */
            instagramUrl?: string | null;
            /** Otherpublic */
            otherPublic?: boolean | null;
            /** Otherurl */
            otherUrl?: string | null;
            /** Xpublic */
            xPublic?: boolean | null;
            /** Xurl */
            xUrl?: string | null;
        };
        /**
         * UserMeResponse
         * @description 本人のプロフィール設定（`PATCH /users/me` の応答）。
         *
         *     id / email / displayName は Phase 1 からある項目で、frontend が名前で
         *     参照している（`features/auth/api.ts`）。**名前と既存の項目は変えずに**
         *     プロフィール拡張の項目を足している。
         */
        UserMeResponse: {
            /** Avatarurl */
            avatarUrl: string | null;
            /** Displayname */
            displayName: string;
            /** Email */
            email: string;
            /** Emailpublic */
            emailPublic: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instagrampublic */
            instagramPublic: boolean;
            /** Instagramurl */
            instagramUrl: string | null;
            /** Otherpublic */
            otherPublic: boolean;
            /** Otherurl */
            otherUrl: string | null;
            /** Xpublic */
            xPublic: boolean;
            /** Xurl */
            xUrl: string | null;
        };
        /** UserPublic */
        UserPublic: {
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * UserPublicProfileResponse
         * @description `GET /users/{id}` で**他人**を取得したときの形（features/profile.md §5）。
         *
         *     ## 公開 OFF の項目は「null」ではなく「キーごと無し」
         *
         *     non-functional.md「データの可視性ルール」は、公開トグル OFF の項目を
         *     **レスポンスに含めない**ことを求めている。`"email": null` と返すと
         *     「メールは設定されているが非公開」という事実まで伝わってしまうため、
         *     キーそのものを落とす。
         *     - `email`: `emailPublic` が ON のときだけキーを出す
         *     - `links`: 常に返す（空なら `{}`）。中身は公開 ON かつ値ありの SNS だけ
         *     - 公開トグルの状態（`emailPublic` など）や URL の生の項目は、他人には一切返さない
         *
         *     `avatarUrl` は公開トグルの対象ではないので、無いときも null で常に返す。
         */
        UserPublicProfileResponse: {
            /** Avatarurl */
            avatarUrl: string | null;
            /** Displayname */
            displayName: string;
            /** Email */
            email?: string | null;
            /** Followercount */
            followerCount: number;
            /** Followingcount */
            followingCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isfollowing */
            isFollowing: boolean;
            links: components["schemas"]["ProfileLinks"];
        };
        /**
         * UserRow
         * @description 一覧の 1 行（アバター + 表示名 + フォロー状態ボタン）。
         */
        UserRow: {
            /** Avatarurl */
            avatarUrl?: string | null;
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isfollowing */
            isFollowing: boolean;
        };
        /** UserRowListResponse */
        UserRowListResponse: {
            /** Items */
            items: components["schemas"]["UserRow"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /**
         * UserSelfProfileResponse
         * @description `GET /users/{id}` で**自分自身**を取得したときの形（features/profile.md §5）。
         *
         *     本人には全項目 ＋ 各公開トグルの状態を返す（プロフィール編集画面で使う）。
         *     設定項目は `UserMeResponse` と同じなので継承し、フォロー数を足す。
         */
        UserSelfProfileResponse: {
            /** Avatarurl */
            avatarUrl: string | null;
            /** Displayname */
            displayName: string;
            /** Email */
            email: string;
            /** Emailpublic */
            emailPublic: boolean;
            /** Followercount */
            followerCount: number;
            /** Followingcount */
            followingCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instagrampublic */
            instagramPublic: boolean;
            /** Instagramurl */
            instagramUrl: string | null;
            /** Isfollowing */
            isFollowing: null;
            /** Otherpublic */
            otherPublic: boolean;
            /** Otherurl */
            otherUrl: string | null;
            /** Xpublic */
            xPublic: boolean;
            /** Xurl */
            xUrl: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    password_reset_confirm_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    password_reset_request_api_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetRequestResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_comment_api_v1_comments__comment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_comment_api_v1_comments__comment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    upload_image_api_v1_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_v1_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_notifications_api_v1_notifications_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    mark_read_api_v1_notifications_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_unread_count_api_v1_notifications_unread_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_feed_api_v1_recipes_get: {
        parameters: {
            query?: {
                feed?: string;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeFeedResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_recipe_api_v1_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_recipe_api_v1_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_recipe_api_v1_recipes__recipe_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_recipe_api_v1_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_comments_api_v1_recipes__recipe_id__comments_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_comment_api_v1_recipes__recipe_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    favorite_recipe_api_v1_recipes__recipe_id__favorite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    unfavorite_recipe_api_v1_recipes__recipe_id__favorite_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    record_recipe_view_api_v1_recipes__recipe_id__view_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_units_api_v1_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitsResponse"];
                };
            };
        };
    };
    delete_me_api_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    put_my_avatar_api_v1_users_me_avatar_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_put_my_avatar_api_v1_users_me_avatar_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_my_avatar_api_v1_users_me_avatar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_my_favorites_api_v1_users_me_favorites_get: {
        parameters: {
            query?: {
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeFeedResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_my_followers_api_v1_users_me_followers_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRowListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_my_following_api_v1_users_me_following_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRowListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_my_history_api_v1_users_me_history_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_my_history_api_v1_users_me_history_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_my_recipes_api_v1_users_me_recipes_get: {
        parameters: {
            query?: {
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSelfProfileResponse"] | components["schemas"]["UserPublicProfileResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    follow_user_api_v1_users__user_id__follow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    unfollow_user_api_v1_users__user_id__follow_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_user_followers_api_v1_users__user_id__followers_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRowListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_user_following_api_v1_users__user_id__following_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRowListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_user_recipes_api_v1_users__user_id__recipes_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListResponse"];
                };
            };
            /** @description リクエストの内容が不正です */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    healthz_db_healthz_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
